steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'asia-northeast1-docker.pkg.dev/$PROJECT_ID/my-repo2/cloud-run-samples:$COMMIT_SHA', '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/my-repo2/cloud-run-samples:$COMMIT_SHA'
    ]

images:
  -  'asia-northeast1-docker.pkg.dev/$PROJECT_ID/my-repo2/cloud-run-samples:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
logsBucket: gs://cloud-run-jobs-samples